name: build Packages

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Grant build script permission
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Create tarball
        run: |
          # Create the tarball in the runner's home directory instead of the repo folder
          # This prevents tar from trying to archive the file it is currently creating
          tar -cJf ../packages-tar.xz --exclude='./.git' .
          mv ../packages-tar.xz .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: build-${{ github.run_number }}
          files: |
            packages-tar.xz
          token: ${{ secrets.GITHUB_TOKEN }}
